# fly.toml app configuration file generated for kiernan-devane-personal on 2026-03-25T14:41:01-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kiernan-devane-personal'
primary_region = 'ewr'

[build]

[[services]]
  protocol = "tcp"
  internal_port = 2222

  [[services.ports]]
    port = 22

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
